clear;
clc;

lats = [46.95, 44.26, 30.06, 8.98, 32.76];
lons = [7.89, -100.47, 110.04, -79.52, -16.96];

names = ["GS-EU", "GS-NA", "GS-AS", "GS-CA", "GS-MA"];
scs = "SCs: " + ["1, 3, 5", "3, 5", "3, 5", "5", "5"];


figure('Name', 'Global Ground Stations', 'Position', [100, 100, 1000, 600]);
gx = geoaxes; 

geobasemap(gx, 'colorterrain'); 
title(gx, 'GS Infrastructure', 'FontSize', 14);
hold on;

for i = 1:length(lats)
    text(gx, lats(i), lons(i), '📡', ...
        'FontSize', 24, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');
    text(gx, lats(i) + 2, lons(i), scs(i), ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'k', ...
        'Color', 'k', ...
        'Margin', 2);
    text(gx, lats(i) + 5, lons(i), names(i), ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'k', ...
        'Color', 'k', ...
        'Margin', 2);
end

hold off;